//-----------------------------------------------------------------

// let num2 = math.floor(num1)
//   essa expressão irá arredondar o valor de baixo para cima

//-----------------------------------------------------------------

// let num2 = math.ceil(num1)
//   essa expressão irá arredondar o valor de cima para baixo

//-----------------------------------------------------------------

// let num2 = math.round(num1)
//   essa expressão irá mostrar o valor da metade para cima

//-----------------------------------------------------------------

// console.log(math.max(1,2,3,4,5,-10,-50,1500,1,4,5))
//   essa expressão ira mostrar o valor maximo = 1500

//-----------------------------------------------------------------

// console.log(math.min(1,2,3,4,5,-10,-50,1500,1,4,5))
//   essa espressão ira mostrar o valor minimo = -50

//-----------------------------------------------------------------

// console.log(math.random() * (10 - 5) + 5)
//   essa expressão ira mostrar um valor aleatorio entre 10 e 5